# Generated by Django 4.0.5 on 2022-07-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_user_managers_chairman_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chairman',
            name='fullname',
        ),
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(default='test user', max_length=150),
        ),
    ]
