# Generated by Django 4.0.5 on 2022-07-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_chairman_fullname_user_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(default='test user', max_length=150, unique=True),
        ),
    ]
