# Generated by Django 4.0.5 on 2022-07-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_user_new_email_user_new_email_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fullname',
            field=models.CharField(default='test user', max_length=150),
        ),
    ]
